AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GeneratePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GeneratePost
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 10
      CodeUri: .
      Environment:
        Variables:
          MODEL_ID: "anthropic.claude-3-sonnet-20240229-v1:0"
          MY_AWS_REGION: "ap-south-1"
      Policies:
        - Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"
      Events:
        ApiPost:
          Type: Api
          Properties:
            Path: /generate-post
            Method: post
        ApiOptions:
          Type: Api
          Properties:
            Path: /generate-post
            Method: options
